version: "3.9"
services:
  webapi:
    build:
      context: src/Product.Api/
      dockerfile: Dockerfile
    ports:
      - "6969:80"
    environment:
      - ProductApi_ConnectionStrings__DefaultConnection=Server=db;Database=MyCompany;User=sa;Password=Password123%
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "42069:1433"
    environment:
      SA_PASSWORD: Password123%
      ACCEPT_EULA: "Y"
